# use Mix.Config
import Config

# Configure your database
config :authie, Authie.Repo,
  username: "hugo",
  password: "",
  database: "authie_dev",
  hostname: "localhost",
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we use it
# with webpack to recompile .js and .css sources.
config :authie, AuthieWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [
    node: [
      "node_modules/webpack/bin/webpack.js",
      "--mode",
      "development",
      "--watch-stdin",
      cd: Path.expand("../assets", __DIR__)
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Note that this task requires Erlang/OTP 20 or later.
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :authie, AuthieWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/authie_web/{live,views}/.*(ex)$",
      ~r"lib/authie_web/templates/.*(eex)$"
    ]
  ]

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :ueberauth, Ueberauth,
  providers: [
    facebook: { Ueberauth.Strategy.Facebook, [
      default_scope: "email, public_profile, user_friends",
      profile_fields: "name, email, first_name, last_name",
      request_path: "/en/auth/facebook",
      callback_path: "/en/auth/facebook/callback"
      ]
    },
    facebook: { Ueberauth.Strategy.Facebook, [
      default_scope: "email, public_profile, user_friends",
      profile_fields: "name, email, first_name, last_name",
      request_path: "/pt/auth/facebook",
      callback_path: "/pt/auth/facebook/callback"
      ]
    },
    identity: { Ueberauth.Strategy.Identity, [
      callback_methods: ["POST"],
      request_path: "/en/auth/identity",
      callback_path: "/en/auth/identity/callback"
    ]},
    identity: { Ueberauth.Strategy.Identity, [
      callback_methods: ["POST"],
      request_path: "/pt/auth/identity",
      callback_path: "/pt/auth/identity/callback"
    ]}
  ],
  json_library: Jason,
  base_path: "/:locale/auth"

config :ueberauth, Ueberauth.Strategy.Facebook.OAuth,
  client_id: System.get_env("FACEBOOK_CLIENT_ID"),
  client_secret: System.get_env("FACEBOOK_CLIENT_SECRET")

# https://github.com/ueberauth/ueberauth/issues/87
config :oauth2,
  serializers: %{
    "application/vnd.api+json" => Jason,
    "application/json" => Jason
  }
